In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
print(arr.dtype)

int64


In [5]:
arr2 = np.array([1,2,3,4,5], dtype=np.int16)

In [6]:
arr2

array([1, 2, 3, 4, 5], dtype=int16)

In [7]:
Z=np.zeros(5)

In [8]:
Z

array([0., 0., 0., 0., 0.])

In [10]:
ar = np.arange(0, 10, 1)

In [11]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
ran=np.random.rand(4)

In [13]:
ran

array([0.64074169, 0.18229047, 0.1499137 , 0.7413901 ])

In [14]:
ln=np.linspace(0,100,10)
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [15]:
arr= np.array([1,2,3,4,5])

In [16]:
arr

array([1, 2, 3, 4, 5])

**2D array**


In [17]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
z1=np.zeros([5,5])

In [20]:
z1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
o1=np.ones([5,5])

In [22]:
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
I=np.eye(5)

In [24]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
r1=np.random.rand(4,5)

In [26]:
r1

array([[0.34328292, 0.91149267, 0.21212042, 0.47783723, 0.96219263],
       [0.50728553, 0.66371474, 0.11036608, 0.4991026 , 0.27952079],
       [0.00236536, 0.26468521, 0.32285927, 0.73163596, 0.11317982],
       [0.48206119, 0.61374019, 0.14959227, 0.98094578, 0.115008  ]])

In [27]:
print(ar.size)

10


In [28]:
print(ar2.size)

9


In [29]:
print(ar2.shape)

(3, 3)


In [30]:
print(ar.shape)

(10,)


**Operations in Array**

copy

sort

reshape

In [31]:
ar3=np.copy(ar2)

In [32]:
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
ar3[2,2]=10

In [34]:
ar3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [35]:
ar3[1,2]=12
ar3[0,1]=15

In [36]:
ar3

array([[ 1, 15,  3],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [37]:
ar3=np.sort(ar3)

In [38]:
ar3

array([[ 1,  3, 15],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [39]:
ar3=np.sort(ar3,axis=0)

In [40]:
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [41]:
ar3.sum()

65

In [42]:
ar3.sum(axis=0)

array([12, 16, 37])

In [43]:
ar3.sum(axis=1)

array([14, 21, 30])

In [45]:
ar4=np.random.rand(99)

In [46]:
ar4

array([0.68282201, 0.72770054, 0.70819057, 0.82254022, 0.38818671,
       0.0777998 , 0.99983882, 0.61134887, 0.89653285, 0.26941195,
       0.60836954, 0.43401499, 0.64535192, 0.43834584, 0.04906806,
       0.16394469, 0.25938438, 0.87276172, 0.40355457, 0.95717883,
       0.59609184, 0.67763802, 0.11417585, 0.14160853, 0.33746496,
       0.27959044, 0.56302233, 0.13990988, 0.15162597, 0.61967039,
       0.85460103, 0.82595215, 0.23023689, 0.2735403 , 0.29694881,
       0.48827005, 0.33417312, 0.6228617 , 0.55046623, 0.13922434,
       0.10817023, 0.21683576, 0.97532105, 0.27229911, 0.79753201,
       0.48051278, 0.65399204, 0.47569647, 0.95826668, 0.13342102,
       0.3924091 , 0.36016192, 0.38844097, 0.36792327, 0.73827885,
       0.87470225, 0.44220715, 0.61310625, 0.26765509, 0.71511124,
       0.63848678, 0.39879251, 0.05633505, 0.29904848, 0.60987159,
       0.57775354, 0.5597074 , 0.61074506, 0.69530041, 0.38440133,
       0.4828438 , 0.16440732, 0.80825096, 0.16476203, 0.10012

In [47]:
ar4.size

99

In [48]:
ar4.reshape(11,9)

array([[0.68282201, 0.72770054, 0.70819057, 0.82254022, 0.38818671,
        0.0777998 , 0.99983882, 0.61134887, 0.89653285],
       [0.26941195, 0.60836954, 0.43401499, 0.64535192, 0.43834584,
        0.04906806, 0.16394469, 0.25938438, 0.87276172],
       [0.40355457, 0.95717883, 0.59609184, 0.67763802, 0.11417585,
        0.14160853, 0.33746496, 0.27959044, 0.56302233],
       [0.13990988, 0.15162597, 0.61967039, 0.85460103, 0.82595215,
        0.23023689, 0.2735403 , 0.29694881, 0.48827005],
       [0.33417312, 0.6228617 , 0.55046623, 0.13922434, 0.10817023,
        0.21683576, 0.97532105, 0.27229911, 0.79753201],
       [0.48051278, 0.65399204, 0.47569647, 0.95826668, 0.13342102,
        0.3924091 , 0.36016192, 0.38844097, 0.36792327],
       [0.73827885, 0.87470225, 0.44220715, 0.61310625, 0.26765509,
        0.71511124, 0.63848678, 0.39879251, 0.05633505],
       [0.29904848, 0.60987159, 0.57775354, 0.5597074 , 0.61074506,
        0.69530041, 0.38440133, 0.4828438 , 0.16440732],


In [49]:
ar4.size

99

In [50]:
ar4.shape

(99,)

In [51]:
ar4=ar4.reshape(11,9)

In [52]:
ar4.size

99

In [53]:
ar4.shape

(11, 9)

In [55]:
ar4=ar4.ravel()

In [56]:
ar4

array([0.68282201, 0.72770054, 0.70819057, 0.82254022, 0.38818671,
       0.0777998 , 0.99983882, 0.61134887, 0.89653285, 0.26941195,
       0.60836954, 0.43401499, 0.64535192, 0.43834584, 0.04906806,
       0.16394469, 0.25938438, 0.87276172, 0.40355457, 0.95717883,
       0.59609184, 0.67763802, 0.11417585, 0.14160853, 0.33746496,
       0.27959044, 0.56302233, 0.13990988, 0.15162597, 0.61967039,
       0.85460103, 0.82595215, 0.23023689, 0.2735403 , 0.29694881,
       0.48827005, 0.33417312, 0.6228617 , 0.55046623, 0.13922434,
       0.10817023, 0.21683576, 0.97532105, 0.27229911, 0.79753201,
       0.48051278, 0.65399204, 0.47569647, 0.95826668, 0.13342102,
       0.3924091 , 0.36016192, 0.38844097, 0.36792327, 0.73827885,
       0.87470225, 0.44220715, 0.61310625, 0.26765509, 0.71511124,
       0.63848678, 0.39879251, 0.05633505, 0.29904848, 0.60987159,
       0.57775354, 0.5597074 , 0.61074506, 0.69530041, 0.38440133,
       0.4828438 , 0.16440732, 0.80825096, 0.16476203, 0.10012

In [57]:
ar3=ar3.T
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [58]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.append(ar,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
ar=np.append(ar,10)

In [62]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
ar=np.delete(ar,6,axis=0)

In [64]:
ar

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10])

In [65]:
ar=np.insert(ar,6,6)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**concatenate**

In [66]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
ar3



array([[ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [68]:
ar4=np.concatenate((ar2,ar3),axis=0)
ar4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [82]:
ar5=np.concatenate((ar2,ar3),axis=1)
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])

In [74]:
ar6=np.split(ar4,3)

In [75]:
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [10, 12, 15]])]

In [76]:
ar[0]

0

In [77]:
ar6[1]

array([[7, 8, 9],
       [1, 4, 7]])

In [78]:
ar6[2]

array([[ 3,  5,  8],
       [10, 12, 15]])

In [80]:
ar6[0][0][0]

1

**Scaler Addition**

add

subtract

multiply

divide

power



In [83]:
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])

In [84]:
np.add(ar5,1)

array([[ 2,  3,  4,  2,  5,  8],
       [ 5,  6,  7,  4,  6,  9],
       [ 8,  9, 10, 11, 13, 16]])

In [85]:
np.subtract(ar5,2)

array([[-1,  0,  1, -1,  2,  5],
       [ 2,  3,  4,  1,  3,  6],
       [ 5,  6,  7,  8, 10, 13]])

In [86]:
np.multiply(ar5,2)

array([[ 2,  4,  6,  2,  8, 14],
       [ 8, 10, 12,  6, 10, 16],
       [14, 16, 18, 20, 24, 30]])

In [87]:
np.divide(ar5,3)

array([[0.33333333, 0.66666667, 1.        , 0.33333333, 1.33333333,
        2.33333333],
       [1.33333333, 1.66666667, 2.        , 1.        , 1.66666667,
        2.66666667],
       [2.33333333, 2.66666667, 3.        , 3.33333333, 4.        ,
        5.        ]])

In [88]:
np.power(ar5,2)

array([[  1,   4,   9,   1,  16,  49],
       [ 16,  25,  36,   9,  25,  64],
       [ 49,  64,  81, 100, 144, 225]])

In [89]:
np.add(ar5,ar5)

array([[ 2,  4,  6,  2,  8, 14],
       [ 8, 10, 12,  6, 10, 16],
       [14, 16, 18, 20, 24, 30]])

**Vector Operations**

In [90]:
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [10, 12, 15]])]

In [91]:
ar7 = np.add(ar6[0],ar6[1])
ar7

array([[ 8, 10, 12],
       [ 5,  9, 13]])

In [92]:
ar8 = np.multiply(ar6[0],ar6[1])
ar8

array([[ 7, 16, 27],
       [ 4, 20, 42]])

In [93]:
ar9 = np.divide(ar6[0],ar6[1])
ar9

array([[0.14285714, 0.25      , 0.33333333],
       [4.        , 1.25      , 0.85714286]])

In [94]:
np.ceil(ar9)

array([[1., 1., 1.],
       [4., 2., 1.]])

In [95]:
np.floor(ar9)

array([[0., 0., 0.],
       [4., 1., 0.]])

In [96]:
np.round(ar9)

array([[0., 0., 0.],
       [4., 1., 1.]])

**Statistics**

In [97]:
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])

In [98]:
np.mean(ar5)

6.111111111111111

In [99]:
np.mean(ar5,axis=0)

array([ 4.        ,  5.        ,  6.        ,  4.66666667,  7.        ,
       10.        ])

In [100]:
np.mean(ar5,axis=1)

array([ 3.        ,  5.16666667, 10.16666667])

In [101]:
np.median(ar5)


5.5

In [102]:
np.median(ar5,axis=0)

array([4., 5., 6., 3., 5., 8.])

In [103]:
np.median(ar5,axis=1)

array([2.5, 5. , 9.5])

In [104]:
np.min(ar5)

1

In [105]:
np.min(ar5,axis=0)

array([1, 2, 3, 1, 4, 7])

In [108]:
np.max(ar5)

15

In [109]:
np.max(ar5,axis=0)

array([ 7,  8,  9, 10, 12, 15])

In [110]:
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])

In [111]:
ar10=np.array([2,5,3,8,0,4,1,6,9])

In [112]:
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])

In [113]:
ar10

array([2, 5, 3, 8, 0, 4, 1, 6, 9])

In [114]:
np.argmax(ar10)

8

In [115]:
np.argmin(ar10)

4

In [116]:
np.argsort(ar10)

array([4, 6, 0, 2, 5, 1, 7, 3, 8])

In [117]:
np.sin(ar10)

array([ 0.90929743, -0.95892427,  0.14112001,  0.98935825,  0.        ,
       -0.7568025 ,  0.84147098, -0.2794155 ,  0.41211849])

In [118]:
np.sin(45)

0.8509035245341184

In [119]:
np.sin(180)

-0.8011526357338304

In [120]:
np.sin(0)

0.0

In [121]:
np.log(10)

2.302585092994046

In [122]:
np.log(1)

0.0

In [124]:
np.log(ar10)

<ipython-input-124-d3b222a67530>:1: RuntimeWarning: divide by zero encountered in log
  np.log(ar10)


array([0.69314718, 1.60943791, 1.09861229, 2.07944154,       -inf,
       1.38629436, 0.        , 1.79175947, 2.19722458])