In [1]:
import numpy as np

In [22]:
ar1=np.array([[85,90,78],[92,88,95],[76,95,85],[90,85,92],[88,76,89]])

In [23]:
ar1

array([[85, 90, 78],
       [92, 88, 95],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [42]:
ar2=np.mean(ar1, axis=1)

In [43]:
ar2

array([84.33333333, 91.66666667, 85.33333333, 89.        , 84.33333333])

In [41]:
np.median(ar1, axis=0)

array([88., 88., 89.])

In [44]:
np.max(ar2)

91.66666666666667

1

In [30]:
np.max(ar1, axis=0)

array([92, 95, 95])

In [31]:
np.min(ar1, axis=0)

array([76, 76, 78])

In [32]:
np.reshape(ar1, (3,5))

array([[85, 90, 78, 92, 88],
       [95, 76, 95, 85, 90],
       [85, 92, 88, 76, 89]])

In [34]:
np.sort(ar1, axis=0)

array([[76, 76, 78],
       [85, 85, 85],
       [88, 88, 89],
       [90, 90, 92],
       [92, 95, 95]])

In [77]:
sum=np.sum(ar1, axis=1)
print(max(sum))
index=np.argmax(sum)
high=ar1[index]
print(high)

275
[92 88 95]
